name: Firefly III
description: Firefly III is a (self-hosted) manager for your personal finances.
version: 1.0
category: Finances
maintainer: Stefan Kuhn
projectURL: https://github.com/Semptic/rancher-catalog.git
