version: '2'

services:
    minecraft:
        image: semptic/minecraft-sponge
        user: ${MC_USER}
        environment:
         - EULA=${EULA}
         - MC_VERSION=${MC_VERSION}
         - SPONGE_VERSION=${SPONGE_VERSION}
         - FORGE_VERSION=${FORGE_VERSION}
         - JAVA_OPTS=${JAVA_OPTS}
        volumes:
         - ${STORAGE}:/minecraft
