version: '2'

catalog:
  name: minecraft
  version: 2.0
  description: Minecraft
  questions:
   - variable: MC_USER
      label: Uid of the user to run under
      type: string
      required: true
      default: 1000
   - variable: EULA
     label: Accept the eula
     required: true
     default: false
     type: boolean   
   - variable: RCON_PW
     label: Rcon password
     type: password
     required: true
   - variable: MOTD
     label: motd message
     type: string
     required: true
   - variable: STORAGE
     label: Local storage path for the minecraft data
     type: string
     required: true
   - variable: MC_VERSION
     label: Minecraft version
     type: string
     required: true
   - variable: SPONGE_VERSION
     label: Version of sponge
     type: string
     required: true
   - variable: FORGE_VERSION
     label: Forge version
     type: string
     required: true
     default: latest
   - variable: JAVA_OPTS
     label: Java options
     type: string
     default: -Xms1G -Xmx8G -XX:+UseG1GC -server

services:
  minecraft:
    scale: 1
    start_on_create: true

