version: '2'

services:
    nginx:
        image: nginx:alpine
        links:
         - nextcloud
        command: /bin/bash -c "echo \"${NGINX_CONFIG}\" > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    nextcloud:
        image: nextcloud:fpm
        links:
         - nextcloud-db
        volumes:
         - nextcloud_apps:/var/www/html/custom_apps
         - nextcloud_config:/var/www/html/config
         - nextcloud_data:/var/www/html/data
    nextcloud-db:
        image: postgres:alpine
        environment:
         - POSTGRES_PASSWORD=${DB_PASS}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_DB=${POSTGRES_DB}
        volumes:
         - nextcloud-db_data:/var/lib/postgresql/data/

volumes:
    nextcloud_apps:
        driver: convoy
    nextcloud_config:
        driver: convoy
    nextcloud_data:
        driver: convoy
    nextcloud-db_data:
        driver: convoy
