version: '2'

services:
    nextcloud:
        image: wonderfall/nextcloud
        links:
         - nextcloud-db
        environment:
         - ADMIN_USER=${ADMIN_USER}
         - ADMIN_PASSWORD=${ADMIN_PASS}
         - DB_TYPE=pgsql
         - DB_NAME=${DB_NAME}
         - DB_PASSWORD=${DB_PASS}
         - DB_USER=${DB_USER}
         - DB_HOST=nextcloud-db
        volumes:
         - nextcloud_data:/apps2
         - nextcloud_data:/config
         - nextcloud_data:/data
    nextcloud-db:
        image: postgres:alpine
        environment:
         - POSTGRES_PASSWORD=${DB_PASS}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_DB=${DB_NAME}
        volumes:
         - nextcloud_data:/var/lib/postgresql/data/

volumes:
    nextcloud_data:
        driver: convoy
