version: '2'

services:
    nextcloud:
        image: nextcloud
        links:
            - db
        volumes:
         - nextcloud_apps:/var/www/html/custom_apps
         - nextcloud_config:/var/www/html/config
         - nextcloud_data:/var/www/html/data
    nextcloud-db:
        image: postgres:alpine
        environment:
         - POSTGRES_PASSWORD=${DB_PASS}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_DB=${POSTGRES_DB}
        volumes:
         - nextcloud-db_dat:/var/lib/postgresql/data

volumes:
    nextcloud_apps:
        driver: convoy
    nextcloud_config:
        driver: convoy
    nextcloud_data:
        driver: convoy
    nextcloud-db_data:
        driver: convoy
